package io.github.tsnee.hpack

import scala.collection.immutable.Queue

private[hpack] object StaticTable extends IndexTable(
  Queue(
    // From RCF 7541 Appendix A
    HeaderField(":authority", "", Indexing.Without),
    HeaderField(":method", "GET", Indexing.Without),
    HeaderField(":method", "POST", Indexing.Without),
    HeaderField(":path", "/", Indexing.Without),
    HeaderField(":path", "/index.html", Indexing.Without),
    HeaderField(":scheme", "http", Indexing.Without),
    HeaderField(":scheme", "https", Indexing.Without),
    HeaderField(":status", "200", Indexing.Without),
    HeaderField(":status", "204", Indexing.Without),
    HeaderField(":status", "206", Indexing.Without),
    HeaderField(":status", "304", Indexing.Without),
    HeaderField(":status", "400", Indexing.Without),
    HeaderField(":status", "404", Indexing.Without),
    HeaderField(":status", "500", Indexing.Without),
    HeaderField("accept-charset", "", Indexing.Without),
    HeaderField("accept-encoding", "gzip, deflate", Indexing.Without),
    HeaderField("accept-language", "", Indexing.Without),
    HeaderField("accept-ranges", "", Indexing.Without),
    HeaderField("accept", "", Indexing.Without),
    HeaderField("access-control-allow-origin", "", Indexing.Without),
    HeaderField("age", "", Indexing.Without),
    HeaderField("allow", "", Indexing.Without),
    HeaderField("authorization", "", Indexing.Without),
    HeaderField("cache-control", "", Indexing.Without),
    HeaderField("content-disposition", "", Indexing.Without),
    HeaderField("content-encoding", "", Indexing.Without),
    HeaderField("content-language", "", Indexing.Without),
    HeaderField("content-length", "", Indexing.Without),
    HeaderField("content-location", "", Indexing.Without),
    HeaderField("content-range", "", Indexing.Without),
    HeaderField("content-type", "", Indexing.Without),
    HeaderField("cookie", "", Indexing.Without),
    HeaderField("date", "", Indexing.Without),
    HeaderField("etag", "", Indexing.Without),
    HeaderField("expect", "", Indexing.Without),
    HeaderField("expires", "", Indexing.Without),
    HeaderField("from", "", Indexing.Without),
    HeaderField("host", "", Indexing.Without),
    HeaderField("if-match", "", Indexing.Without),
    HeaderField("if-modified-since", "", Indexing.Without),
    HeaderField("if-none-match", "", Indexing.Without),
    HeaderField("if-range", "", Indexing.Without),
    HeaderField("if-unmodified-since", "", Indexing.Without),
    HeaderField("last-modified", "", Indexing.Without),
    HeaderField("link", "", Indexing.Without),
    HeaderField("location", "", Indexing.Without),
    HeaderField("max-forwards", "", Indexing.Without),
    HeaderField("proxy-authenticate", "", Indexing.Without),
    HeaderField("proxy-authorization", "", Indexing.Without),
    HeaderField("range", "", Indexing.Without),
    HeaderField("referer", "", Indexing.Without),
    HeaderField("refresh", "", Indexing.Without),
    HeaderField("retry-after", "", Indexing.Without),
    HeaderField("server", "", Indexing.Without),
    HeaderField("set-cookie", "", Indexing.Without),
    HeaderField("strict-transport-security", "", Indexing.Without),
    HeaderField("transfer-encoding", "", Indexing.Without),
    HeaderField("user-agent", "", Indexing.Without),
    HeaderField("vary", "", Indexing.Without),
    HeaderField("via", "", Indexing.Without),
    HeaderField("www-authenticate", "", Indexing.Without)
  )
)
